### ISSUE TITLE
Image post element should inherit sensible defaults from attachment

### ISSUE THREAD

**Issue by goldenapples** [fusioneng/image-shortcake#12]
When adding a shortcode using *Insert Post Element*,  the shortcode fields should inherit default values that were entered on the attachment. Likely will require extending Shortcake to support default values and events on attribute fields.

**Comment by goldenapples** [comment]
From discussion today with @mkeppel : 

> Matt Keppel 
> [10:10 AM] 
> ![screen_shot_2015-04-28_at_1 14 00_pm](https://cloud.githubusercontent.com/assets/665992/7377596/3e705ce8-ed9c-11e4-9339-a821c2507a79.png)
> 
> Matt Keppel [10:10 AM] 
> So you are still working on getting these fields to work properly right?
> 
> Matt Keppel [10:10 AM]
> How/what will they do? as images should have them already
> 
> Nathaniel Taintor [10:12 AM] 
> Yeah, that requires some deeper work in Shortcake to integrate, as there isn’t currently any functionality in Shortcake to set defaults like that.
> 
> Nathaniel Taintor [10:12 AM]
> What *should* happen is that those should be populated with defaults from the image once an image is selected.
> 
> Matt Keppel [10:13 AM] 
> Great and default should be centered and full width Just making sure we are on the same page
> 
> Matt Keppel [10:13 AM]
> I am not seeing the share buttons on mobile
> 
> Nathaniel Taintor [10:14 AM] 
> Right, those were removed a little while back after there was an issue about share links on comics..
> 
> Nathaniel Taintor [10:14 AM]
> It would not be hard to enable them for other post formats, just need someone to make that call.
> 
> Matt Keppel [10:15 AM] 
> Yes we would need this on mobile just not comics and galleries at the moment
> 
> Nathaniel Taintor [10:16 AM] 
> OK, I will add that in.
> 
> Matt Keppel [10:17 AM] 
> Great Just confrmed with lisa about that design as well we are still fans of it for mobiel jsut not on comics or galleries
> 
> Matt Keppel [10:19 AM]
> How much work/time do you think it will be to get the fields below the images working?
> 
> Matt Keppel [10:20 AM]
> I would not feel comfortable pushing this until they work as edit team uses the float left and float right options
> 
> Nathaniel Taintor [10:21 AM] 
> Ah. Those should be working by later today. I’ll prioritize that above the migrate script.

**Comment by danielbachhuber** [comment]
@davisshaver FYI - This is already WIP in #44

**Comment by davisshaver** [comment]
Picking this up today.

So we have used the new Shortcake hooks to add actions to the `img.attachment` and `img.linkto` listeners, which then call eponymously named functions within the `ImageShortcake` var.

To complete the integration, we'll need to add a similar hook to the `img.credit` listener, which should then call a function in `ImageShortcakeIntegration` to try and populate the credit from attachment object.

cc @goldenapples, lemme know if anything seems off in this plan.

**Comment by goldenapples** [comment]
Actually, I think its the other way around. We'd need to attach another action to the `img.attachment` change event, so that whenever the attachment field is changed, we update the credit field's value if (1) there isn't already a value set and (2) there is a credit field on the attachment.

You can use the listeners in #44 as a model. Since "credit" isn't a standard field, though, that function needs to live in our theme instead of in the plugin. 

As far as I'm concerned, #44 can be merged now. I was waiting on https://github.com/fusioneng/Shortcake/pull/358 to be finished, but that's merged now and it should all work now...

**Comment by davisshaver** [comment]
@goldenapples I agree re: mergeability of this branch.

Here's what I have so far for the integration branch: https://github.com/fusioneng/fusion-theme/issues/3681

**Comment by davisshaver** [comment]
@mkeppel Assigning to you for product review.
