### ISSUE TITLE
Alignment left and alignment right break the preview

### ISSUE THREAD

**Issue by danielbachhuber** [fusioneng/image-shortcake#23]
When I align an image left or right, the image disappears from view. I believe this is because the image is floated, and doesn't have any height.

Ideally, we'd be able to align images and have text wrap around them. However, TinyMCE views doesn't support this: https://github.com/fusioneng/Shortcake/issues/9

For the time being, we'll likely just need to clear to ensure the image always previews.

**Comment by goldenapples** [comment]
See https://github.com/fusioneng/Shortcake/pull/320 for a possible solution. If that's too nuclear of an approach, I can address it just for the shortcode from this plugin with a function hooked on 'shortcode_ui_after_do_shortcode' that outputs a clearing <br> tag or something of the sort.

**Comment by goldenapples** [comment]
This was addressed in https://github.com/fusioneng/Shortcake/pull/320 and shouldn't need special attaention here anymore.
