### ISSUE TITLE
Editing an image doesn't have my custom image size

### ISSUE THREAD

**Issue by danielbachhuber** [fusioneng/image-shortcake#24]
When I insert an image in the Fusion theme, I'm presented with these sizes:

![image](https://cloud.githubusercontent.com/assets/36432/7502161/cab7325a-f3ee-11e4-95fb-e6f82a645c29.png)

However, when I edit, I only see these sizes:

![image](https://cloud.githubusercontent.com/assets/36432/7502171/d7c4e26c-f3ee-11e4-87b5-8733de7ed616.png)

The custom size is added through a filter (which I can't recall of the top of my head) that we'll need to apply against this image size option.

**Comment by goldenapples** [comment]
Closed from #27.
