### ISSUE TITLE
HTML5

### ISSUE THREAD

**Issue by ninetienne** [fusioneng/image-shortcake#46]
Guys, you should really make the HTML5 markup with `<figure>` and `<figcaption>`. Thanks!

**Comment by goldenapples** [comment]
Hmm. It should be supported already. The output is done through core's `img_caption_shortcode`, which will output figure/figcaption tags if the current theme declares support for HTML5 captions, and div/p tags if not.

It looks like it uses `current_theme_supports( 'html5', 'caption' )` as the check: https://github.com/WordPress/WordPress/blob/master/wp-includes/media.php#L903,L906

**Comment by ninetienne** [comment]
Yep, sorry, seems it outputs figure for images with caption only, while single images without captions are returned only as img without any wrapper. Thanks!

**Comment by davisshaver** [comment]
:8ball:

**Comment by danielbachhuber** [comment]
@ninetienne just to clarify, is this working as expected, or is there something we should fix?

**Comment by ninetienne** [comment]
@danielbachhuber all is good! Nothing to fix here.
