### ISSUE TITLE
Clarify that double quotes breaks captions and credits

### ISSUE THREAD

**Issue by danielbachhuber** [fusioneng/image-shortcake#51]
Because double quotes will break the shortcode, we should have some language explaining single quotes should be used instead.

**Comment by swissspidy** [comment]
See also #42

**Comment by davisshaver** [comment]
This is gnarly and reveals the major flaw with using shortcodes for rich text content, like captions.

There's really _nothing_ we could do to prevent a user from typing into the HTML editor [img attachment="99" caption="This is my awesome caption about the photo of Donald Trump, who said, "This is an awesome picture.""]. 

Such a limitation (or, to the user, :bug:) seems _tolerable_ for a credit, but intolerable for a caption. Within Fusion theme, we already warn users that quote marks and HTML tags are not allowed for credits when viewing Insert Image context. I'll make a new PR to do the same for Insert Media context.

What would it take to move the caption to inner content? That way we get ourselves out of the caption issue.

**Comment by davisshaver** [comment]
This was a Fusion theme issue that has been merged in https://github.com/fusioneng/fusion-theme/issues/3656

**Comment by danielbachhuber** [comment]
> This was a Fusion theme issue that has been merged

It's still applicable with the plugin, no?

**Comment by davisshaver** [comment]
@danielbachhuber The plugin already has the warning? https://github.com/fusioneng/image-shortcake/blob/master/inc/class-img-shortcode.php#L82

**Comment by montchr** [comment]
As a user of this plugin, I should say that the warning would be appreciated, as it's an issue with the plugin (well, shortcodes inherently) and not a specific theme. You have the message in your theme but it's still an issue for other themes, meaning that each theme will need to add this message. And most probably won't do so, meaning that people will continue running into this issue.

**Comment by montchr** [comment]
But @davisshaver I do see that it's included in the plugin, it's just that most editors will probably use the standard media library uploader, which doesn't display the warning.

**Comment by danielbachhuber** [comment]
> it's just that most editors will probably use the standard media library uploader, which doesn't display the warning.

☝️

**Comment by davisshaver** [comment]
On it

**Comment by davisshaver** [comment]
Actually I will come back to this issue later in image shortcake work. The code to add the disclaimer for the field has already been merged, and it's not straightforward to pull it out. Will keep it open for now.

**Comment by danielbachhuber** [comment]
:ship:

**Comment by montchr** [comment]
:cake:
