### ISSUE TITLE
Create a WP-CLI command to convert inline images to shortcodes

### ISSUE THREAD

**Issue by danielbachhuber** [fusioneng/image-shortcake#8]
It should perform inline transformations, and offer a `--dry-run` option so the developer can see how it will operate without performing the actual transformations.

Because there's a high cost to failure, the logged output should include before and after for each transformation, should you need to fix stuff from the logs.

WP-CLI has a [functional test framework](https://github.com/wp-cli/wp-cli/wiki/Package-Functional-Tests) we can use for functional tests.

**Comment by goldenapples** [comment]
This was addressed in #14.
